# Generated by Django 5.2.9 on 2026-02-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("inventory", "Inventory Report"),
                            ("orders", "Orders Report"),
                            ("customers", "Customer Report"),
                            ("products", "Product Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_file", models.BinaryField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_receipt",
                        to="shop.order",
                    ),
                ),
            ],
        ),
    ]
